---
- name: Manage TLS Certificates
  hosts: localhost
  connection: local
  gather_facts: false
  become: false

  tasks:
    - name: Load ACME account configuration
      ansible.builtin.include_vars:
        file: vars/acme_account.yml

    - name: Initialize or verify ACME account
      ansible.builtin.include_tasks: tasks/acme_account.yml

    - name: Issue certificate
      ansible.builtin.include_tasks: tasks/issue_cert.yml
      vars:
        cert_config_file: "{{ item }}"
      with_fileglob:
        - "vars/certs/*.yml"
